services:
  naming-server:
    image: sjovic650/naming-server:latest
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    image: sjovic650/api-gateway:latest
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  users-service:
    image: sjovic650/users-service:latest
    build:
      context: .
      dockerfile: users-service/Dockerfile
    ports:
      - "8770:8770"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  bank-account:
    image: sjovic650/bank-account:latest
    build:
      context: .
      dockerfile: bank-account/Dockerfile
    ports:
      - "8200:8200"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  crypto-wallet:
    image: sjovic650/crypto-wallet:latest
    build:
      context: .
      dockerfile: crypto-wallet/Dockerfile
    ports:
      - "8300:8300"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  currency-exchange:
    image: sjovic650/currency-exchange:latest
    build:
      context: .
      dockerfile: currency-exchange/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  crypto-exchange:
    image: sjovic650/crypto-exchange:latest
    build:
      context: .
      dockerfile: crypto-exchange/Dockerfile
    ports:
      - "8400:8400"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  currency-conversion:
    image: sjovic650/currency-conversion:latest
    build:
      context: .
      dockerfile: currency-conversion/Dockerfile
    ports:
      - "8100:8100"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

  trade-service:
    image: sjovic650/trade-service:latest
    build:
      context: .
      dockerfile: trade-service/Dockerfile
    ports:
      - "8600:8600"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
