server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion,/currency-conversion/**
          filters:
            - BasicAuth
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/trade-service,/trade-service/**
          filters:
            - BasicAuth
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - BasicAuth
        - id: bank-account
          uri: lb://bank-account
          predicates:
            - Path=/bank-accounts/**
          filters:
            - BasicAuth
        - id: crypto-wallet
          uri: lb://crypto-wallet
          predicates:
            - Path=/crypto-wallets/**
          filters:
            - BasicAuth
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange,/currency-exchange/**
        - id: crypto-exchange
          uri: lb://crypto-exchange
          predicates:
            - Path=/crypto-exchange,/crypto-exchange/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
